### ISSUE TITLE
python manage.py collectstatic installs devDependencies

### ISSUE THREAD

**Issue by Andrioden** [whitespy/django-node-assets#8]
As the title indicate, static collection also installs devDepdencies, this bloats the static folder immensely.

My suggestion is that it by default dont do this, i believe you need to do something like `npm install --omit=dev` ([ref](https://stackoverflow.com/questions/9268259/how-do-you-prevent-install-of-devdependencies-npm-modules-for-node-js-package))

package.json
```
  "dependencies": {
    "jquery": "^3.7.0"
  },
  "devDependencies": {
    "@jest/globals": "^29.3.1",
    "@types/jquery": "^3.5.16",
    "@types/jquery.slimscroll": "^1.3.31",
    "@types/jqueryui": "^1.12.16",
    "@types/kineticjs": "^0.0.29",
    "eslint": "^8.30.0",
    "eslint-config-standard": "^17.0.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsdoc": "^39.6.4",
    "eslint-plugin-n": "^15.6.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-simple-import-sort": "^8.0.0",
    "jest": "^29.3.1",
    "jsdom": "^20.0.3",
    "typescript": "^4.9.4"
  },
```

`python manage.py collectstatic` output
![image](https://github.com/whitespy/django-node-assets/assets/393376/7b2cac78-0af9-4d63-9357-0059fd726b82)

**Comment by fedaya** [comment]
Hi, I hope you since have found the solution since.
As I had to look through the code to find out, it looks like you might want to use the `'django_node_assets.finders.ManifestNodeModulesFinder'` instead of the default `'django_node_assets.finders.NodeModulesFinder'`.

It only will find direct dependencies, though. for example, with `bootstrap` dependency, `@popperjs/core` won't be discovered, unless you specify it in you `package.json`

**Comment by Andrioden** [comment]
I ended up using a different library: https://github.com/kevin1024/django-npm.

**Comment by deeprave** [comment]
Hi @Andrioden,

While django-npm is good it is pretty much unmaintained which is a pity (I reworked a fork in the repo `Uniquode/django-npm` if you're interested). The downside is that it isn't very selective about what is copied into staticfiles and requires configuration rather than directly sourcing package.json.

Being able to customise the npm command line (and use yarn and/or pnpm) is something I would like to see in django-node-assets, and will make some time to submit a PR for it soon. That would effectively solve your problem.

**Comment by whitespy** [comment]
Hello, everybody. The version 0.9.14 no longer installs dev dependencies.
